[project]
name = "triton-puzzles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jaxtyping>=0.3.4",
    "numpy>=2.4.0",
    "pycairo>=1.29.0",
    "torch",
    "triton",
]
